"""Alter ExtendedWorkHours ou name altered

Revision ID: 573c320ad8e5
Revises: a310133a285c
Create Date: 2024-10-09 16:36:37.782235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573c320ad8e5'
down_revision: Union[str, None] = 'a310133a285c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extended_workhours', sa.Column('ou', sa.Integer(), nullable=True))
    op.drop_column('extended_workhours', 'business_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extended_workhours', sa.Column('business_unit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('extended_workhours', 'ou')
    # ### end Alembic commands ###
