"""Try to added Column into StandardWorkhours

Revision ID: 7fd9b4722ce5
Revises: 9b9f6fd3f5f6
Create Date: 2024-10-03 17:03:05.408198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fd9b4722ce5'
down_revision: Union[str, None] = '9b9f6fd3f5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extended_workhours', 'extension_start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('extended_workhours', 'extension_end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.add_column('standard_workhours', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('standard_workhours', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('standard_workhours', sa.Column('session_termination_action', sa.String(), nullable=True))
    op.alter_column('standard_workhours', 'allowed_work',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.drop_column('standard_workhours', 'starttime')
    op.drop_column('standard_workhours', 'termination_action')
    op.drop_column('standard_workhours', 'ou')
    op.drop_column('standard_workhours', 'endtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_workhours', sa.Column('endtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('standard_workhours', sa.Column('ou', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('standard_workhours', sa.Column('termination_action', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('standard_workhours', sa.Column('starttime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('standard_workhours', 'allowed_work',
               existing_type=sa.String(length=15),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('standard_workhours', 'session_termination_action')
    op.drop_column('standard_workhours', 'end_time')
    op.drop_column('standard_workhours', 'start_time')
    op.alter_column('extended_workhours', 'extension_end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('extended_workhours', 'extension_start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
