"""Trying to make ExtendedWorkHours id auto-incremement

Revision ID: 8fef37db43d5
Revises: d3abff02e621
Create Date: 2024-10-10 09:36:22.529222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fef37db43d5'
down_revision: Union[str, None] = 'd3abff02e621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
