"""Alter ExtendedWorkHours exteou name altered

Revision ID: a310133a285c
Revises: 1d5f4a18b0de
Create Date: 2024-10-09 16:12:02.302093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a310133a285c'
down_revision: Union[str, None] = '1d5f4a18b0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extended_workhours', sa.Column('uid', sa.String(), nullable=True))
    op.add_column('extended_workhours', sa.Column('c', sa.Integer(), nullable=False))
    op.drop_column('extended_workhours', 'userid')
    op.drop_column('extended_workhours', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extended_workhours', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('extended_workhours', sa.Column('userid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('extended_workhours', 'c')
    op.drop_column('extended_workhours', 'uid')
    # ### end Alembic commands ###
