"""Deactivated table removed and add column deactivation_date into StandardWorkHours

Revision ID: efe58ede32d1
Revises: ab5decd34dc8
Create Date: 2024-10-11 11:54:03.693454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe58ede32d1'
down_revision: Union[str, None] = 'ab5decd34dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_workhours', sa.Column('deactivation_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_workhours', 'deactivation_date')
    # ### end Alembic commands ###
