"""Try to add all tables

Revision ID: fb7f51a00649
Revises: 
Create Date: 2024-10-03 11:15:05.504905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb7f51a00649'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('client_version', sa.String(length=50), nullable=False),
    sa.Column('os_name', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=False),
    sa.Column('agent_info', sa.String(length=50), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('holiday_date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('holiday_type', sa.String(length=2), nullable=False),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('holiday_date')
    )
    op.create_table('standard_workhours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', postgresql.CITEXT(), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=False),
    sa.Column('endtime', sa.DateTime(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('st', sa.String(length=35), nullable=False),
    sa.Column('c', sa.Integer(), nullable=False),
    sa.Column('weekdays', sa.String(length=7), nullable=False),
    sa.Column('termination_action', sa.String(length=20), nullable=False),
    sa.Column('cn', sa.String(length=240), nullable=True),
    sa.Column('l', sa.String(length=240), nullable=True),
    sa.Column('unrestricted', sa.Boolean(), nullable=True),
    sa.Column('ou', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deactivated',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('std_wrk_id', sa.Integer(), nullable=False),
    sa.Column('uid', postgresql.CITEXT(), nullable=True),
    sa.Column('cn', sa.String(length=240), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['std_wrk_id'], ['standard_workhours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extended_workhours',
    sa.Column('indexes', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('std_wrk_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(), nullable=True),
    sa.Column('extension_start_time', sa.DateTime(), nullable=False),
    sa.Column('extension_end_time', sa.DateTime(), nullable=False),
    sa.Column('extended_workhours_type', sa.String(length=2), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('city', sa.Integer(), nullable=False),
    sa.Column('week_days_count', sa.String(length=7), nullable=False),
    sa.Column('extension_active', sa.Integer(), nullable=False),
    sa.Column('business_unit', sa.Integer(), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['std_wrk_id'], ['standard_workhours.id'], ),
    sa.PrimaryKeyConstraint('indexes')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('std_wrk_id', sa.Integer(), nullable=False),
    sa.Column('userid', postgresql.CITEXT(), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['std_wrk_id'], ['standard_workhours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('std_wrk_id', sa.Integer(), nullable=False),
    sa.Column('id_target', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=37), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_target'], ['target.id'], ),
    sa.ForeignKeyConstraint(['std_wrk_id'], ['standard_workhours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=35), nullable=True),
    sa.Column('create_timestamp', sa.DateTime(), nullable=False),
    sa.Column('update_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('target_status')
    op.drop_table('sessions')
    op.drop_table('messages')
    op.drop_table('extended_workhours')
    op.drop_table('deactivated')
    op.drop_table('target')
    op.drop_table('standard_workhours')
    op.drop_table('holidays')
    op.drop_table('exceptions')
    op.drop_table('client')
    # ### end Alembic commands ###
