"""Change column name into StandardWorkhours

Revision ID: fba3667f2737
Revises: 7fd9b4722ce5
Create Date: 2024-10-03 17:31:46.551627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fba3667f2737'
down_revision: Union[str, None] = '7fd9b4722ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deactivated', 'uid',
               existing_type=postgresql.CITEXT(),
               nullable=False)
    op.add_column('exceptions', sa.Column('type', sa.String(length=50), nullable=True))
    op.drop_column('exceptions', 'tipo')
    op.add_column('messages', sa.Column('uid', postgresql.CITEXT(), nullable=True))
    op.drop_column('messages', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('userid', postgresql.CITEXT(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'uid')
    op.add_column('exceptions', sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('exceptions', 'type')
    op.alter_column('deactivated', 'uid',
               existing_type=postgresql.CITEXT(),
               nullable=True)
    # ### end Alembic commands ###
