"""Alter ExtendedWorkHours extensions_time to datetime.

Revision ID: 1d5f4a18b0de
Revises: 2333a1e72d8f
Create Date: 2024-10-08 17:01:53.778986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d5f4a18b0de'
down_revision: Union[str, None] = '2333a1e72d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extended_workhours', 'extension_start_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('extended_workhours', 'extension_end_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extended_workhours', 'extension_end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('extended_workhours', 'extension_start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
