"""Alter  StandardWorkhours to StandardWorkHours[c] to String(100)

Revision ID: 2333a1e72d8f
Revises: 4538b4e52127
Create Date: 2024-10-04 17:59:24.407579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2333a1e72d8f'
down_revision: Union[str, None] = '4538b4e52127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deactivated', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('extended_workhours', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('extended_workhours', 'indexes')
    op.alter_column('messages', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('standard_workhours', 'c',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('target_status', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('target_status', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('standard_workhours', 'c',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('messages', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('extended_workhours', sa.Column('indexes', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('extended_workhours', 'id')
    op.alter_column('deactivated', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
