"""Alter  StandardWorkhours to StandardWorkHours, alter Deactivated[std_wrk_id] to nullable.

Revision ID: 4538b4e52127
Revises: fba3667f2737
Create Date: 2024-10-04 15:29:34.611643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4538b4e52127'
down_revision: Union[str, None] = 'fba3667f2737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deactivated', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deactivated', 'std_wrk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
