"""Try to added Column into StandardWorkhours

Revision ID: 9b9f6fd3f5f6
Revises: fb7f51a00649
Create Date: 2024-10-03 14:51:44.323949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9f6fd3f5f6'
down_revision: Union[str, None] = 'fb7f51a00649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_workhours', sa.Column('allowed_work', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_workhours', 'allowed_work')
    # ### end Alembic commands ###
