"""Every date to Datetime

Revision ID: 9fa2f417966f
Revises: 8fef37db43d5
Create Date: 2024-10-10 11:00:05.857565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fa2f417966f'
down_revision: Union[str, None] = '8fef37db43d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deactivated', sa.Column('deactivation_date', sa.DateTime(), nullable=False))
    op.alter_column('extended_workhours', 'extension_start_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('extended_workhours', 'extension_end_time',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extended_workhours', 'extension_end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('extended_workhours', 'extension_start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.drop_column('deactivated', 'deactivation_date')
    # ### end Alembic commands ###
