"""Alter ExtendedWorkHours datetimes to date

Revision ID: c65dad6abff7
Revises: 573c320ad8e5
Create Date: 2024-10-09 17:42:20.025676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65dad6abff7'
down_revision: Union[str, None] = '573c320ad8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
