"""added new atributes for holiday

Revision ID: 9625b04343ff
Revises: e6a50a3744ab
Create Date: 2024-11-21 15:54:24.555584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9625b04343ff'
down_revision: Union[str, None] = 'e6a50a3744ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('holidays', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('holidays', sa.Column('day', sa.Integer(), nullable=False))
    op.add_column('holidays', sa.Column('month', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'holidays', ['name'])
    op.drop_column('holidays', 'holiday_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('holiday_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'holidays', type_='unique')
    op.drop_column('holidays', 'month')
    op.drop_column('holidays', 'day')
    op.drop_column('holidays', 'name')
    op.drop_column('holidays', 'id')
    # ### end Alembic commands ###
