"""change type for start_time,end_time, allowed_workhours and default for session_termination_action

Revision ID: 985b1e9131f2
Revises: 2839e44e3d16
Create Date: 2024-11-20 23:27:51.929838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '985b1e9131f2'
down_revision: Union[str, None] = '2839e44e3d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_workhours', sa.Column('allowed_work_hours', sa.Text(), nullable=True))
    op.alter_column('standard_workhours', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('standard_workhours', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('standard_workhours', 'cn',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.create_unique_constraint(None, 'standard_workhours', ['uid'])
    op.drop_column('standard_workhours', 'allowed_work')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_workhours', sa.Column('allowed_work', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'standard_workhours', type_='unique')
    op.alter_column('standard_workhours', 'cn',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.alter_column('standard_workhours', 'end_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('standard_workhours', 'start_time',
               existing_type=sa.String(length=5),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('standard_workhours', 'allowed_work_hours')
    # ### end Alembic commands ###
